### ISSUE TITLE
Error when click on title

### ISSUE THREAD

**Issue by Fa10175** [Tywed/news-menu#10]
I've just tried your news-menu-0.2.2.zip module with webtrees 2.1.18 and 2.1.20
here is the display:

![Screenshot 2024-05-05 at 10-56-41 News – webtrees](https://github.com/Tywed/news-menu/assets/10681601/726c05ff-ec44-456a-8736-8546e3b53fe1)

when I click on the title "2024" I get this display:

![Screenshot 2024-05-05 at 10-38-04 News – webtrees](https://github.com/Tywed/news-menu/assets/10681601/a17912ef-a861-4a9f-830e-60f2ec750515)

**Comment by Tywed** [comment]
This error occurs due to short PHP opening tags that some hosting sites do not support. In update 2.2. replaced all short tags with full ones. It was only in main. Thank you for noticing and informing me that there is an error in the release. I'll update it now.

**Comment by Tywed** [comment]
Update it - https://github.com/Tywed/news-menu/releases/tag/v0.2.3
