### ISSUE TITLE
Does not appear

### ISSUE THREAD

**Issue by SteveEngelking** [Tywed/news-menu#12]
I've added the module successfully and News module is ticked but only the simple news module appears. Am I missing something?
The module does not appear in the Genealogy/Menus section so it cannot be ticked.
I'm running the latest webtrees version and webtrees theme.

**Comment by SteveEngelking** [comment]
The module does not appear in the Genealogy/Menus section so it cannot be ticked.

**Comment by SteveEngelking** [comment]
Solved this by changing module name to NewsMenu
However comments option does not appear.

**Comment by SteveEngelking** [comment]
I changed language and behold it all appeared correctly!
Thanks for a super module.

**Comment by SteveEngelking** [comment]
Solved

**Comment by kiwi3685** [comment]
In comments here the solution given is "Solved this by changing module name to NewsMenu"

Can this be added to the ReadMe page. I've just wasted time trying to fix the same problem. Took me a while to even think to search closed issues. I don't regard this as closed yet.
